- name: Configure firewall
  firewall:
    service: "{{ item.service | default(omit) }}"
    port: "{{ item.port | default(omit)}}"
    trust: "{{ item.trust | default(omit)}}"
    trust_by_mac: "{{ item.trust_by_mac | default(omit)}}"
    masq: "{{ item.masq | default(omit)}}"
    masq_by_mac: "{{ item.masq_by_mac | default(omit)}}"
    forward_port: "{{ item.forward_port | default(omit)}}"
    forward_port_by_mac: "{{ item.forward_port_by_mac | default(omit)}}"    
    state: "{{ item.state }}"

  with_items:
    - "{{ firewall }}"
